### ISSUE TITLE
Investigate Wordnet topics

### ISSUE THREAD

**Issue by DavidLeoni** [diversicon-kb/diversicon-website#3]

**Comment by gbella** [comment]
So far I didn't manage to find any serious documentation on WordNet topics strictly speaking.
However, there is material on the general topic of domain categories for lexical resources:

- WordNet Domains: http://wndomains.fbk.eu/hierarchy.html
- related paper: http://wndomains.fbk.eu/publications/Coling-04-ws-WDH.pdf
- yet to be investigated: WordNet topics, EuroWordNet domains.

It seems that the somewhat ad-hoc original WordNet Domains hierarchy was updated, according to the paper above, to conform better to certain theoretical criteria as well as to existing authoritative document classification schemes, in particular the Dewey Decimal System. The paper above contains an annex describing the first two levels of the updated WordNet Domains hierarchy. The full tree of the updated hierarchy does not seem to be freely available online.

The way to go seems to be to adopt one of the authoritative classification schemes such as the DDC or Colon Classification. The updated WND hierarchy, if we can find it, would be a very good candidate.

**Comment by DavidLeoni** [comment]
I reviewed a bit [some classification systems](https://en.wikipedia.org/wiki/Library_classification). Full classifications usually have closed license but make available a summary with more permissive licence.

|System|License|Summary|Pros|Cons|
|----------|-----------|------------|------|-------|
|[DDC](https://en.wikipedia.org/wiki/Dewey_Decimal_Classification)|closed+|[summary available](https://www.oclc.org/dewey/features/summaries.en.html), not so clear how can be reused|widely used, regularly updated, has just 10 top domains|Closed license, unclear summary reuse terms|
|[Universal Decimal Classification](http://www.udcc.org/) [Wikipedia](https://en.wikipedia.org/wiki/Universal_Decimal_Classification)|[closed](http://www.udcc.org/index.php/site/page?view=licences) open ++|[summary available and reusable](http://www.udcsummary.info/php/index.php), [RDF available](http://udcdata.info/)|clear license, summary open, regularly updated, has just 10 top domains, rdf available|Closed license|
|[Library of Congress](https://en.wikipedia.org/wiki/Library_of_Congress_Classification)| TODO|TODO |TODO|TODO|
|[Colon Classification](https://en.wikipedia.org/wiki/Colon_classification)|TODO |TODO  |TODO | Mainly used in India.  Seems the official reference is a book. Even hard to find a reference website...|
|[BISAC](https://bisg.site-ym.com/page/BISACEdition)|closed+++|[available but not reusable](http://bisg.org/page/bisacedition) | TODO | to use it you gotta pay|

+: [from Dewey FAQ](http://staff.oclc.org/~dewey/dewey.htm)
++:  [from UDC licence](http://www.udcc.org/index.php/site/page?view=licences): "You do not need a licence to use UDC if  you want to publish, distribute or use in any other way the 2,600 classes published in the UDC Summary."  
+++: BISAC you can freely access the online list, but you [need to pay](https://bisg.site-ym.com/page/PurchaseBISAC)  to reuse it in your own databases

**Comment by DavidLeoni** [comment]
Will choose UDC, on the website we will put just top categories
